[project]
name = "singtown-ai-trainer-yolov5rk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.8.4",
    "numpy==1.21.6",
    "onnx==1.14.0",
    "onnxoptimizer==0.2.7",
    "opencv-python==4.5.5.64",
    "pandas>=1.5.1",
    "pillow==9.5.0",
    "seaborn>=0.13.2",
    "setuptools==59.5.0",
    "singtown-ai>=1.10.1",
    "tensorboard>=2.20.0",
    "torch==1.13.1",
    "torchvision==0.14.1",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]
torchvision = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
